### ISSUE TITLE
CI: ansible-lint 

### ISSUE THREAD

**Issue by quotengrote** [Azubis-Dataport-Magdeburg/dp_ausb_md#399]
## Welche Komponente ist defekt?
Der ansible-linter in den GitHUb-Actions läuft nicht mehr + lokal das selbe problem.

## Fehlerbeschreibung:
```bash
+ ansible-lint -v --force-color
Traceback (most recent call last):
  File "/usr/local/bin/ansible-lint", line 5, in <module>
    from ansiblelint.__main__ import main
  File "/usr/local/lib/python3.8/site-packages/ansiblelint/__main__.py", line 37, in <module>
    from ansiblelint.generate_docs import rules_as_rich, rules_as_rst
  File "/usr/local/lib/python3.8/site-packages/ansiblelint/generate_docs.py", line 6, in <module>
    from rich.console import render_group
ImportError: cannot import name 'render_group' from 'rich.console' (/usr/local/lib/python3.8/site-packages/rich/console.py)
```
## Wie kann der Fehler nachgestellt werden? (Schritt für Schritt)
CI ausführen

**Comment by quotengrote** [comment]
vmtl: https://github.com/ansible/ansible-lint-action/issues/41

**Comment by quotengrote** [comment]
warte auf Fix im Upstream
